#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Nov 12 11:06:07 2009

import wx
import atom
import gdata.contacts
import gdata.contacts.service

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel = wx.Panel(self, -1)
        self.sizerCOntactos_staticbox = wx.StaticBox(self.panel, -1, u"Contactos:")
        self.sizerCalendarios_staticbox = wx.StaticBox(self.panel, -1, u"Calendarios:")
        self.sizerLogin_staticbox = wx.StaticBox(self.panel, -1, u"Conexión a Google")
        self.labelAgenda = wx.StaticText(self.panel, -1, u"Agenda")
        self.static_line_1 = wx.StaticLine(self.panel, -1)
        self.labelUsuario = wx.StaticText(self.panel, -1, u"Usuario", style=wx.ALIGN_RIGHT)
        self.usuario = wx.TextCtrl(self.panel, -1, "")
        self.labelPasswd = wx.StaticText(self.panel, -1, u"Passwd:", style=wx.ALIGN_RIGHT)
        self.passwd = wx.TextCtrl(self.panel, -1, u"", style=wx.TE_PASSWORD)
        self.btnLogin = wx.Button(self.panel, -1, u"&Conectar")
        self.listContactos = wx.ListBox(self.panel, -1, choices=[], style=wx.LB_SINGLE|wx.LB_ALWAYS_SB)
        self.labelNombre = wx.StaticText(self.panel, -1, u"Nombre:")
        self.nombre = wx.TextCtrl(self.panel, -1, "")
        self.labelCorreo = wx.StaticText(self.panel, -1, u"Correo:")
        self.text_ctrl_1 = wx.TextCtrl(self.panel, -1, u"")
        self.labelTe = wx.StaticText(self.panel, -1, u"Teléfono:")
        self.telefono = wx.TextCtrl(self.panel, -1, u"")
        self.labelOrga = wx.StaticText(self.panel, -1, u"Organización:")
        self.orga = wx.TextCtrl(self.panel, -1, u"")
        self.labelWebsite = wx.StaticText(self.panel, -1, u"Sitio web:")
        self.website = wx.TextCtrl(self.panel, -1, u"")
        self.labelNotas = wx.StaticText(self.panel, -1, u"Notas:")
        self.notas = wx.TextCtrl(self.panel, -1, u"")
        self.btnActualizar = wx.Button(self.panel, -1, u"Ac&tualizar")
        self.listCalendarios = wx.ListBox(self.panel, -1, choices=[], style=wx.LB_ALWAYS_SB)
        self.labelEvento = wx.StaticText(self.panel, -1, u"Evento:")
        self.evento = wx.TextCtrl(self.panel, -1, u"")
        self.labelFecha = wx.StaticText(self.panel, -1, u"Fecha:")
        self.fecha = wx.DatePickerCtrl(self.panel, -1)
        self.labelHora = wx.StaticText(self.panel, -1, u"Hora:")
        self.comboHora = wx.ComboBox(self.panel, -1, choices=[], style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.labelLugar = wx.StaticText(self.panel, -1, u"Lugar:")
        self.lugar = wx.TextCtrl(self.panel, -1, u"")
        self.labelDescripcion = wx.StaticText(self.panel, -1, u"Descripción:")
        self.descripcion = wx.TextCtrl(self.panel, -1, u"")
        self.labelEspaciador1 = wx.StaticText(self.panel, -1, u"")
        self.labelEspaciador2 = wx.StaticText(self.panel, -1, u"")
        self.btnActualizarCalendario = wx.Button(self.panel, -1, u"Act&ualizar:")
        self.labelSeparadorBotones = wx.StaticText(self.panel, -1, u"")
        self.btnCancelar = wx.Button(self.panel, wx.ID_CANCEL, u"")
        self.btnOk = wx.Button(self.panel, wx.ID_OK, u"")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnConectarGoogle, self.btnLogin)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnSelectContactos, self.listContactos)
        self.Bind(wx.EVT_LISTBOX, self.OnListContactos, self.listContactos)
        self.Bind(wx.EVT_BUTTON, self.OnActualizarContactos, self.btnActualizar)
        self.Bind(wx.EVT_LISTBOX_DCLICK, self.OnSeleccionarCalendarios, self.listCalendarios)
        self.Bind(wx.EVT_LISTBOX, self.OnCalendarios, self.listCalendarios)
        self.Bind(wx.EVT_BUTTON, self.OnActualizarCalendario, self.btnActualizarCalendario)
        self.Bind(wx.EVT_BUTTON, self.OnCancelar, self.btnCancelar)
        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.btnOk)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(u"Sancabase - Agenda")
        self.SetSize((803, 553))
        self.labelAgenda.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade
        self.CenterOnScreen()

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizerPpal = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizerCalendarios = wx.StaticBoxSizer(self.sizerCalendarios_staticbox, wx.HORIZONTAL)
        sizerCalendarioEdit2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizerCOntactos = wx.StaticBoxSizer(self.sizerCOntactos_staticbox, wx.HORIZONTAL)
        sizerContactoEdit2 = wx.BoxSizer(wx.VERTICAL)
        sizerContactoEdit1 = wx.BoxSizer(wx.VERTICAL)
        sizerLogin = wx.StaticBoxSizer(self.sizerLogin_staticbox, wx.HORIZONTAL)
        sizer_1.Add(self.labelAgenda, 0, 0, 0)
        sizer_1.Add(self.static_line_1, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        sizerLogin.Add(self.labelUsuario, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 2)
        sizerLogin.Add(self.usuario, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        sizerLogin.Add(self.labelPasswd, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL, 20)
        sizerLogin.Add(self.passwd, 0, wx.LEFT|wx.RIGHT|wx.ALIGN_CENTER_VERTICAL, 5)
        sizerLogin.Add(self.btnLogin, 0, wx.LEFT|wx.ALIGN_CENTER_VERTICAL, 50)
        sizer_1.Add(sizerLogin, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        sizerCOntactos.Add(self.listContactos, 1, wx.ALL|wx.EXPAND, 4)
        sizerContactoEdit1.Add(self.labelNombre, 0, wx.ALL, 2)
        sizerContactoEdit1.Add(self.nombre, 0, wx.ALL|wx.EXPAND, 2)
        sizerContactoEdit1.Add(self.labelCorreo, 0, wx.ALL, 2)
        sizerContactoEdit1.Add(self.text_ctrl_1, 0, wx.ALL|wx.EXPAND, 2)
        sizerContactoEdit1.Add(self.labelTe, 0, wx.ALL, 2)
        sizerContactoEdit1.Add(self.telefono, 0, wx.ALL|wx.EXPAND, 2)
        sizerCOntactos.Add(sizerContactoEdit1, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizerContactoEdit2.Add(self.labelOrga, 0, wx.ALL, 2)
        sizerContactoEdit2.Add(self.orga, 0, wx.ALL|wx.EXPAND, 2)
        sizerContactoEdit2.Add(self.labelWebsite, 0, wx.ALL, 2)
        sizerContactoEdit2.Add(self.website, 0, wx.ALL|wx.EXPAND, 2)
        sizerContactoEdit2.Add(self.labelNotas, 0, wx.ALL, 2)
        sizerContactoEdit2.Add(self.notas, 0, wx.ALL|wx.EXPAND, 2)
        sizerCOntactos.Add(sizerContactoEdit2, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizerCOntactos.Add(self.btnActualizar, 0, wx.ALL|wx.ALIGN_BOTTOM, 2)
        sizer_1.Add(sizerCOntactos, 0, wx.RIGHT|wx.BOTTOM|wx.EXPAND, 5)
        sizerCalendarios.Add(self.listCalendarios, 1, wx.ALL|wx.EXPAND, 4)
        sizer_4.Add(self.labelEvento, 0, wx.ALL, 2)
        sizer_4.Add(self.evento, 0, wx.ALL|wx.EXPAND, 2)
        sizer_4.Add(self.labelFecha, 0, wx.ALL, 2)
        sizer_4.Add(self.fecha, 0, wx.ALL|wx.EXPAND, 2)
        sizer_4.Add(self.labelHora, 0, wx.ALL, 2)
        sizer_4.Add(self.comboHora, 0, wx.ALL|wx.EXPAND, 2)
        sizerCalendarios.Add(sizer_4, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizerCalendarioEdit2.Add(self.labelLugar, 0, wx.ALL, 2)
        sizerCalendarioEdit2.Add(self.lugar, 0, wx.ALL|wx.EXPAND, 2)
        sizerCalendarioEdit2.Add(self.labelDescripcion, 0, wx.ALL, 2)
        sizerCalendarioEdit2.Add(self.descripcion, 0, wx.ALL|wx.EXPAND, 2)
        sizerCalendarioEdit2.Add(self.labelEspaciador1, 0, wx.ALL, 2)
        sizerCalendarioEdit2.Add(self.labelEspaciador2, 0, wx.ALL, 2)
        sizerCalendarios.Add(sizerCalendarioEdit2, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizerCalendarios.Add(self.btnActualizarCalendario, 0, wx.ALL|wx.ALIGN_BOTTOM, 2)
        sizer_1.Add(sizerCalendarios, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        sizer_2.Add(self.labelSeparadorBotones, 0, wx.LEFT|wx.EXPAND, 590)
        sizer_2.Add(self.btnCancelar, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        sizer_2.Add(self.btnOk, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)
        self.panel.SetSizer(sizer_1)
        sizerPpal.Add(self.panel, 0, wx.EXPAND, 0)
        self.SetSizer(sizerPpal)
        self.Layout()
        # end wxGlade

    def OnConectarGoogle(self, event): # wxGlade: MyFrame.<event_handler>
        self.gd_client = gdata.contacts.service.ContactsService()
        email = self.usuario.GetValue()
        password = self.passwd.GetValue()
        self.gd_client.email = email
        self.gd_client.password = password
        try:
            logueo = self.gd_client.ProgrammaticLogin()
            #feed = self.gd_client.GetContactsFeed()
            query = gdata.contacts.service.ContactsQuery()
            query.max_results = 1000
            query['sortorder'] = 'ascending'
            feed = self.gd_client.GetContactsFeed(query.ToUri())
            fed = str(feed)
            f = open('/home/javier/Escritorio/feed.xml', 'w')
            f.write(fed)
            f.close()
            contactos = []
            for entry in feed.entry:
                if entry.title.text == None:
                    entry.title.text = u'Desconocido' 
                contactos.append(entry.title.text)
            for contacto in contactos:
                self.listContactos.Append(contacto)
        except:
            dlg = wx.MessageDialog(self, u"Verifique usuario y contraseña e intente nuevamente",
             u"Error de login", wx.OK | wx.ICON_ERROR)
            dlg.ShowModal()
            dlg.Destroy()

            
    def OnSelectContactos(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnSelectContactos' not implemented!"
        event.Skip()

    def OnListContactos(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnListContactos' not implemented!"
        event.Skip()

    def OnActualizarContactos(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnActualizarContactos' not implemented!"
        event.Skip()

    def OnSeleccionarCalendarios(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnSeleccionarCalendarios' not implemented!"
        event.Skip()

    def OnCalendarios(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnCalendarios' not implemented!"
        event.Skip()

    def OnActualizarCalendario(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnActualizarCalendario' not implemented!"
        event.Skip()

    def OnCancelar(self, event): # wxGlade: MyFrame.<event_handler>
        self.Close()

    def OnAceptar(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnAceptar' not implemented!"
        event.Skip()

# end of class MyFrame


class Agenda(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame = MyFrame(None, -1, u"")
        self.SetTopWindow(frame)
        frame.Show()
        return 1

# end of class Agenda

if __name__ == "__main__":
    app = Agenda(0)
    app.MainLoop()
