#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jan  4 12:15:35 2010

import wx
import sqlite3 as sql3

# begin wxGlade: extracode
# end wxGlade



class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.labelCert = wx.StaticText(self, -1, u"Datos para confección de certificados:")
        self.cursos = []
        self.db = sql3.connect("sancabase2.db")
        c = self.db.cursor()
        c.execute ('''SELECT num_curso FROM cursos order by num_curso''')
        q = c.fetchall()
        c.close()
        for curso in q:
            self.cursos.append(curso[0])
        self.labelNumCurso = wx.StaticText(self, -1, u"Número de curso:")
        self.comboNumCurso = wx.ComboBox(self, -1, choices=self.cursos,
         style=wx.CB_DROPDOWN|wx.CB_DROPDOWN|wx.CB_READONLY)
        self.labelMargenX = wx.StaticText(self, -1, "Margen X: ")
        self.spinX = wx.SpinCtrl(self, -1, "17", min=0, max=30)
        self.labelMargenY = wx.StaticText(self, -1, "Margen Y:")
        self.spinY = wx.SpinCtrl(self, -1, "18", min=0, max=30)
        self.btnAceptar = wx.Button(self, wx.ID_APPLY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnConfeccionCertificados, self.btnAceptar)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle(u"Confección de certificados")
        self.SetSize((350, 200))
        self.comboNumCurso.SetValue(self.cursos[0])
        self.comboNumCurso.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 3, 3)
        sizer_1.Add(self.labelCert, 0, wx.TOP|wx.BOTTOM, 10)
        grid_sizer_1.Add(self.labelNumCurso, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.comboNumCurso, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.labelMargenX, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.spinX, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.labelMargenY, 0, wx.ALL, 5)
        grid_sizer_1.Add(self.spinY, 0, wx.ALL, 5)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_1.Add(self.btnAceptar, 0, wx.ALL|wx.ALIGN_RIGHT, 10)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnConfeccionCertificados(self, event): # wxGlade: MyDialog.<event_handler>
        curso = self.comboNumCurso.GetValue()
        x = self.spinX.GetValue()
        y = self.spinY.GetValue()
        f = open('datosConfeccCert', 'w')
        f. write('%s\n' % curso)
        f. write('%s\n' % x)
        f. write('%s' % y)
        f.close()
        self.Destroy()

# end of class MyDialog


class SelecDialogCert(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        dialogCertificados = MyDialog(None, -1, "")
        self.SetTopWindow(dialogCertificados)
        dialogCertificados.Show()
        return 1

# end of class SelecDialogCert

if __name__ == "__main__":
    app = SelecDialogCert(0)
    app.MainLoop()
