#!/usr/bin/env python
# -*- coding: utf-8 -*-
# archivo : legajosocialcargado.py
#
# generated by wxGlade 0.6.3 on Wed Aug 12 20:53:27 2009
#
##############################################################################
#
#
# Sancabase - Administrador general para centros de Formación Profesional
# Copyright (c) 2007 Javier Castrillo // riverplatense at gmail dot com
#Este programa es software libre; usted puede redistruirlo y/o modificarlo bajo
#los términos de la Licencia Pública General GNU, tal y como está publicada
#por la Free Software Foundation; ya sea la versión 2 de la Licencia, o (a su
#elección) cualquier versión posterior.
#
#Este programa se distribuye con la intención de ser útil, pero SIN NINGUNA
#GARANTÍA; incluso sin la garantía implícita de USABILIDAD O UTILIDAD PARA UN
#FIN PARTICULAR. Vea la Licencia Pública General GNU para más detalles.
#
#Usted debería haber recibido una copia de la Licencia Pública General GNU
#junto a este programa; si no es así, escriba a la Free Software Foundation,
#Inc. 675 Mass Ave, Cambridge, MA 02139, EEUU.
#
#
##############################################################################

import wx
import wx.grid
import MySQLdb

# begin wxGlade: extracode
# end wxGlade



class LegajoSocialCargado(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LegajoSocial.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        menuBar = wx.MenuBar()
        menuArchivo = wx.Menu()
        menuBar.Append(menuArchivo, u'&Opciones avanzadas')
        seguimiento = menuArchivo.Append(-1, u'&Seguimiento', u'Abrir un editor de texto para escribir libremente')
        self.SetMenuBar(menuBar)
        self.CreateStatusBar()
        self.SetStatusText(u'Sancabase - Legajo social')
        self.Bind(wx.EVT_MENU, self.OnAbrirArchivo, seguimiento)
        f = open('idLegajoMod', 'r')
        self.id = f.readline()
        f.close()
        self.db = MySQLdb.connect('localhost', 'javier', 'javier', 'escuela', charset='UTF8')
        c = self.db.cursor()
        c.execute ('''SELECT * FROM legajo WHERE id_legajo = %s''' % self.id)
        q = c.fetchone()
        c.close()
        self.idalumnoB = q[1]
        self.nombreB = q[2]
        nac = q[3]
        dia = nac.day
        mes = nac.month
        anio = nac.year
        self.fechanacB = wx.DateTimeFromDMY(dia,mes-1,anio)
        self.nacionalidadB = q[4]
        self.estcivilB = q[5]
        self.domicilioB = q[6]
        self.teB = q[7]
        self.plansocialB = q[8]
        self.queplanB = q[9]
        self.planfamiliarB = q[10]
        self.queplanfamiliarB = q[11]
        self.empleoB = q[12]
        self.ubicacionempleoB = q[13]
        self.educB = q[14]
        self.abandonoB = q[15]
        self.causaabandonoB = q[16]
        self.cursandoB = q[17]
        self.cursandolugarB = q[18]
        self.otroscursosfpB = q[19]
        self.otroscursosfpcualesB = q[20]
        self.jefefamiliaB = q[21]
        self.deportesB = q[22]
        self.deportesdondeB = q[23]
        self.tiempolibreB = q[24]
        self.eligioelcentroB = q[25]
        self.eligioelcursoB = q[26]
        self.judicialesB = q[27]
        self.causasB = q[28]
        self.tratMedB = q[29]
        self.obsB = q[30]
        self.panel = wx.Panel(self, -1)
        self.lblLegajo = wx.StaticText(self.panel, -1, "Legajo Social")
        self.static_line_1 = wx.StaticLine(self.panel, -1)
        self.labelNombre = wx.StaticText(self.panel, -1, "Nombre:")
        self.nombres = wx.TextCtrl(self.panel, -1, "")
        self.labelApellidos = wx.StaticText(self.panel, -1, "Fecha nac.:")
        self.fechaNac = wx.DatePickerCtrl(self.panel, -1)
        self.labelLugarNac = wx.StaticText(self.panel, -1, "Lugar Nac. :")
        self.lugarNac = wx.TextCtrl(self.panel, -1, "")
        self.labelEstadoCivil = wx.StaticText(self.panel, -1, "Estado Civil:")
        self.estadoCivil = wx.ComboBox(self.panel, -1, choices=["Soltero/a", "Casado/a", "En pareja (conviviendo)", "En pareja (sin convivir)", "Separado/a", "Divorciado/a", "Viudo/a"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.labelDomicilio = wx.StaticText(self.panel, -1, "Domicilio:")
        self.domicilio = wx.TextCtrl(self.panel, -1, "")
        self.labelTelefono = wx.StaticText(self.panel, -1, u"Teléfono:")
        self.telefono = wx.TextCtrl(self.panel, -1, "")
        self.checkPlan = wx.CheckBox(self.panel, -1, "Plan Social")
        self.planSocial = wx.ComboBox(self.panel, -1, choices=[u'', u"Plan Trabajar", u"Plan Jefas y jefes", u"Fines"], style=wx.CB_DROPDOWN)
        self.checkPlanFamiliar = wx.CheckBox(self.panel, -1, "Familiar")
        self.planFamiliar = wx.ComboBox(self.panel, -1, choices=[u'',  u"Plan Trabajar", u"Plan Jefas y jefes", u"Fines"], style=wx.CB_DROPDOWN)
        self.labelEmpleo = wx.StaticText(self.panel, -1, "Empleo:")
        self.empleo = wx.ComboBox(self.panel, -1, choices=["Empleado/a  (Rel. dependencia)", u"Empleado/a (Contrato a término)", "Empleado/a  (Informal)", u"Changarín", "Cuentapropista/a", "Empresario/a", "Comerciante", "Empleado/a casa de familia", "Desocupado/a", u'No Aplica'], style=wx.CB_DROPDOWN)
        self.labelEmpresa = wx.StaticText(self.panel, -1, u"Ubicación:")
        self.empresa = wx.TextCtrl(self.panel, -1, "")
        self.labelEduacionFormal = wx.StaticText(self.panel, -1, "Educ. formal:")
        self.educacion = wx.TextCtrl(self.panel, -1, "")
        self.checkAbandono = wx.CheckBox(self.panel, -1, u"Abandonó")
        self.motivoAbandono = wx.TextCtrl(self.panel, -1, "Motivo del mismo...")
        self.checkCursando = wx.CheckBox(self.panel, -1, "Cursando:")
        self.escuelaActual = wx.TextCtrl(self.panel, -1, "Escuela y horarios")
        self.checkFP = wx.CheckBox(self.panel, -1, "Cursos FP:")
        self.cursosFP = wx.TextCtrl(self.panel, -1, "Centro y cursos")
        self.checkJefeFam = wx.CheckBox(self.panel, -1, "Jefe/a familia?")
        self.labelFamilia = wx.StaticText(self.panel, -1, "Grupo Familiar -->")
        self.checkDeporte = wx.CheckBox(self.panel, -1, "Deportes")
        self.deportesdonde = wx.TextCtrl(self.panel, -1, u"Qué deporte y en qué lugar...")
        self.labelTiempoLibre = wx.StaticText(self.panel, -1, "Tiempo libre:")
        self.hobbyes = wx.TextCtrl(self.panel, -1, "")
        self.labelPQCentro = wx.StaticText(self.panel, -1, "Este centro...")
        self.pQCentro = wx.TextCtrl(self.panel, -1, u"... lo elegí por...")
        self.lblPQCurso = wx.StaticText(self.panel, -1, "Este curso...")
        self.pQCurso = wx.TextCtrl(self.panel, -1, u"... lo elegí por...")
        self.checkJudiciales = wx.CheckBox(self.panel, -1, "Judiciales")
        self.judiciales = wx.TextCtrl(self.panel, -1, "Anotaciones...")
        self.labelTratMed = wx.StaticText(self.panel, -1, u"Trat. méd:")
        self.tratMed = wx.TextCtrl(self.panel, -1, "")
        self.labelObs = wx.StaticText(self.panel, -1, "Obs:")
        self.obs = wx.TextCtrl(self.panel, -1, "")
        self.gridFamilia = wx.grid.Grid(self.panel, -1, size=(1, 1))
        self.buttonAceptar = wx.Button(self.panel, wx.ID_APPLY, "")
        self.buttonCancelar = wx.Button(self.panel, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHECKBOX, self.OnPlanSocial, self.checkPlan)
        self.Bind(wx.EVT_CHECKBOX, self.OnPlanFamiliar, self.checkPlanFamiliar)
        self.Bind(wx.EVT_CHECKBOX, self.OnAbandono, self.checkAbandono)
        self.Bind(wx.EVT_CHECKBOX, self.OnCursando, self.checkCursando)
        self.Bind(wx.EVT_CHECKBOX, self.OnFP, self.checkFP)
        self.Bind(wx.EVT_CHECKBOX, self.OnDeporte, self.checkDeporte)
        self.Bind(wx.EVT_CHECKBOX, self.OnJudiciales, self.checkJudiciales)
        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.buttonAceptar)
        self.Bind(wx.EVT_BUTTON, self.OnCancelar, self.buttonCancelar)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LegajoSocial.__set_properties
        self.SetTitle("Sancabase - Legajo Social")
        self.SetSize((800, 600))
        self.CenterOnScreen()
        self.lblLegajo.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, 0, ""))
        self.nombres.SetFocus()
        self.nombres.SetValue(self.nombreB)
        self.domicilio.SetValue(self.domicilioB)
        self.telefono.SetValue(self.teB)
        self.fechaNac.SetValue(self.fechanacB)
        self.lugarNac.SetValue(self.nacionalidadB)
        self.estadoCivil.SetValue(self.estcivilB)
        # Seteo de plan social propio
        if self.plansocialB == 1:
            self.checkPlan.SetValue(True)
            self.planSocial.Enable(True)
            self.planSocial.SetValue(self.queplanB)
        else:
            self.planSocial.Enable(False)
        # Seteo de plan social de algún familiar
        if self.planfamiliarB ==1:
            self.checkPlanFamiliar.SetValue(True)
            self.planFamiliar.Enable(True)
            self.planFamiliar.SetValue(self.queplanfamiliarB)
        else:
             self.planFamiliar.Enable(False)
        self.empleo.SetValue(self.empleoB)
        self.empresa.SetValue(self.ubicacionempleoB)
        self.educacion.SetValue(self.educB)
        # Seteo de abandono de estudios y causa
        if self.abandonoB == 0:
            self.checkAbandono.SetValue(False)
            self.motivoAbandono.Enable(False)
        else:
            self.checkAbandono.SetValue(True)
            self.motivoAbandono.Enable(True)
            self.motivoAbandono.SetValue(self.causaabandonoB)
        # Seteo de estudios en curso
        if self.cursandoB == 0:
            self.checkCursando.SetValue(False)
            self.escuelaActual.Enable(False)
        else:
            self.checkCursando.SetValue(True)
            self.escuelaActual.Enable(True)
            self.escuelaActual.SetValue(self.cursandolugarB)
        # Seteo de cursos de FP
        if self.otroscursosfpB == 0:
            self.checkFP.SetValue(False)
            self.cursosFP.Enable(False)
        else:
            self.checkFP.SetValue(True)
            self.cursosFP.Enable(True)
            self.cursosFP.SetValue(self.otroscursosfpcualesB)
        # Seteo de jefe de familia
        if self.jefefamiliaB == 1:
            self.checkJefeFam.SetValue(True)
        # Seteo de deportes
        if self.deportesB == 0:
            self.checkDeporte.SetValue(False)
            self.deportesdonde.Enable(False)
        else:
            self.checkDeporte.SetValue(True)
            self.deportesdonde.Enable(True)
            self.deportesdonde.SetValue(self.deportesdondeB)
        self.hobbyes.SetValue(self.tiempolibreB)
        self.pQCentro.SetValue(self.eligioelcentroB)
        self.pQCurso.SetValue(self.eligioelcursoB)
        # Seteo de judiciales
        if self.judicialesB == 0:
            self.checkJudiciales.SetValue(False)
            self.judiciales.Enable(False)
        else:
            self.checkJudiciales.SetValue(True)
            self.judiciales.Enable(True)
            self.judiciales.SetValue(self.causasB)
        self.tratMed.SetValue(self.tratMedB)
        self.obs.SetValue(self.obsB)
        self.gridFamilia.CreateGrid(10, 5)
        self.gridFamilia.SetRowLabelSize(0)
        self.gridFamilia.SetColLabelSize(20)
        self.gridFamilia.EnableDragRowSize(0)
        self.gridFamilia.SetColLabelValue(0, "Nombre")
        self.gridFamilia.SetColSize(0, 80)
        self.gridFamilia.SetColLabelValue(1, "Pariente")
        self.gridFamilia.SetColSize(1, 80)
        self.gridFamilia.SetColLabelValue(2, "Edad")
        self.gridFamilia.SetColSize(2, 40)
        self.gridFamilia.SetColLabelValue(3, "Trabaja")
        self.gridFamilia.SetColSize(3, 65)
        self.gridFamilia.SetColLabelValue(4, "Obs")
        self.gridFamilia.SetColSize(4, 90)
        c = self.db.cursor()
        c.execute('''SELECT nombre, parentesco, trabajo, edad,
         obs FROM grupoFam_%s''' % self.idalumnoB)
        datosfam = c.fetchall()
        for renglon, linea in enumerate(datosfam):
            for h in range(5):
                self.gridFamilia.SetCellValue(renglon, h, linea[h])
        c.close()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LegajoSocial.__do_layout
        sizerGrande = wx.BoxSizer(wx.VERTICAL)
        sizerPpal = wx.BoxSizer(wx.VERTICAL)
        sizerBotones = wx.BoxSizer(wx.HORIZONTAL)
        sizerMedio = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(8, 2, 2, 2)
        gridDatosPersonales = wx.FlexGridSizer(15, 2, 2, 2)
        sizerPpal.Add(self.lblLegajo, 0, 0, 0)
        sizerPpal.Add(self.static_line_1, 0, wx.TOP|wx.BOTTOM|wx.EXPAND, 4)
        gridDatosPersonales.Add(self.labelNombre, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.nombres, 0, wx.EXPAND, 0)
        gridDatosPersonales.Add(self.labelApellidos, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.fechaNac, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelLugarNac, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.lugarNac, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelEstadoCivil, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.estadoCivil, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelDomicilio, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.domicilio, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelTelefono, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.telefono, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.checkPlan, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.planSocial, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.checkPlanFamiliar, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.planFamiliar, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelEmpleo, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.empleo, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelEmpresa, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.empresa, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.labelEduacionFormal, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.educacion, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.checkAbandono, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.motivoAbandono, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.checkCursando, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.escuelaActual, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.checkFP, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.cursosFP, 0, wx.ALL|wx.EXPAND, 1)
        gridDatosPersonales.Add(self.checkJefeFam, 0, wx.ALL, 1)
        gridDatosPersonales.Add(self.labelFamilia, 0, wx.ALL|wx.ALIGN_RIGHT, 1)
        gridDatosPersonales.AddGrowableCol(1)
        sizerMedio.Add(gridDatosPersonales, 1, wx.RIGHT|wx.EXPAND, 14)
        grid_sizer_1.Add(self.checkDeporte, 0, wx.ALL, 1)
        grid_sizer_1.Add(self.deportesdonde, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.Add(self.labelTiempoLibre, 0, wx.ALL, 1)
        grid_sizer_1.Add(self.hobbyes, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.Add(self.labelPQCentro, 0, 0, 0)
        grid_sizer_1.Add(self.pQCentro, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.Add(self.lblPQCurso, 0, wx.ALL, 1)
        grid_sizer_1.Add(self.pQCurso, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.Add(self.checkJudiciales, 0, wx.ALL, 1)
        grid_sizer_1.Add(self.judiciales, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.Add(self.labelTratMed, 0, wx.ALL, 1)
        grid_sizer_1.Add(self.tratMed, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.Add(self.labelObs, 0, wx.ALL, 1)
        grid_sizer_1.Add(self.obs, 0, wx.ALL|wx.EXPAND, 1)
        grid_sizer_1.AddGrowableCol(1)
        sizer_4.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_3.Add(sizer_4, 0, wx.LEFT|wx.EXPAND, 10)
        sizer_3.Add(self.gridFamilia, 1, wx.ALL|wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.FIXED_MINSIZE, 9)
        sizerMedio.Add(sizer_3, 1, wx.EXPAND, 0)
        sizerPpal.Add(sizerMedio, 1, wx.EXPAND, 0)
        sizerBotones.Add(self.buttonAceptar, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 8)
        sizerBotones.Add(self.buttonCancelar, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 8)
        sizerPpal.Add(sizerBotones, 0, wx.ALIGN_RIGHT, 0)
        self.panel.SetSizer(sizerPpal)
        sizerGrande.Add(self.panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizerGrande)
        self.Layout()
        # end wxGlade

    def OnPlanSocial(self, event): # wxGlade: LegajoSocial.<event_handler>
        if self.checkPlan.IsChecked():
            self.planSocial.Enable()
            self.planSocial.SetFocus()
        else:
            self.planSocial.Disable()
        
    def OnPlanFamiliar(self, event): # wxGlade: LegajoSocial.<event_handler>
        if self.checkPlanFamiliar.IsChecked():
            self.planFamiliar.Enable()
            self.planFamiliar.SetFocus()
        else:
            self.planFamiliar.Disable()

    def OnAbandono(self, event): # wxGlade: LegajoSocial.<event_handler>
        if self.checkAbandono.IsChecked():
            self.motivoAbandono.Enable()
            self.motivoAbandono.SetFocus()
        else:
            self.motivoAbandono.Disable()

    def OnCursando(self, event): # wxGlade: LegajoSocial.<event_handler>
        if self.checkCursando.IsChecked():
            self.escuelaActual.Enable()
            self.escuelaActual.SetFocus()
        else:
            self.escuelaActual.Disable()

    def OnFP(self, event): # wxGlade: LegajoSocial.<event_handler>
        if self.checkFP.IsChecked():
            self.cursosFP.Enable()
            self.cursosFP.SetFocus()
        else:
            self.cursosFP.Disable()

    def OnDeporte(self, event):
        if self.checkDeporte.IsChecked():
            self.deportesdonde.Enable()
            self.deportesdonde.SetFocus()
        else:
            self.deportesdonde.Disable()


    def OnJudiciales(self, event): # wxGlade: LegajoSocial.<event_handler>
        if self.checkJudiciales.IsChecked():
            self.judiciales.Enable()
            self.judiciales.SetFocus()
        else:
            self.judiciales.Disable()

    def OnAceptar(self, event): # wxGlade: LegajoSocial.<event_handler>
        nombre = self.nombres.GetValue()
        dia = self.fechaNac.GetValue()
        fechanac = ('%04d/%02d/%02d' % (dia.GetYear(), dia.GetMonth()+1, dia.GetDay()))
        lugarNac = self.lugarNac.GetValue()
        estcivil = self.estadoCivil.GetValue()
        domicilio = self.domicilio.GetValue()
        telefono = self.telefono.GetValue()
        if self.checkPlan.IsChecked():
            planSocial = 1
        else:
            planSocial = 0
        queplan = self.planSocial.GetValue()
        if self.checkPlanFamiliar.IsChecked():
            planFamiliar = 1
        else:
            planFamiliar = 0
        queplanfamiliar = self.planFamiliar.GetValue()    
        empleo = self.empleo.GetValue()
        ubicacionempleo = self.empresa.GetValue()
        educformal = self.educacion.GetValue()
        if self.checkAbandono.IsChecked():
            abandono = 1
        else:
            abandono = 0
        causaabandono = self.motivoAbandono.GetValue()
        if self.checkCursando.IsChecked():
            cursando = 1
        else:
            cursando = 0
        cursandolugar = self.escuelaActual.GetValue()
        if self.checkFP.IsChecked():
            otroscursosfp = 1
        else:
            otroscursosfp = 0
        otroscursosfpcuales = self.cursosFP.GetValue()
        if self.checkJefeFam.IsChecked():
            jefefamilia = 1
        else:
            jefefamilia = 0
        if self.checkDeporte.IsChecked():
            deportes = 1
        else:
            deportes = 1
        deportesdonde = self.deportesdonde.GetValue()
        tiempolibre = self.hobbyes.GetValue()
        eligioelcentro = self.pQCentro.GetValue()
        eligioelcurso = self.pQCurso.GetValue()
        if self.checkJudiciales.IsChecked():
            judiciales = 1
        else:
            judiciales = 0
        causas = self.judiciales.GetValue()
        tratmedico = self.tratMed.GetValue()
        observaciones = self.obs.GetValue()
        c = self.db.cursor()
        c.execute('''UPDATE legajo SET id_alumno = %s, nombre = %s, fechanac = %s, lugarnac = %s,
         estcivil = %s, domicilio = %s, te = %s, plansocial = %s, queplan = %s, planfamiliar = %s,
         queplanfamiliar = %s, empleo = %s, ubicacionempleo = %s, educformal = %s, 
         abandono = %s, causaabandono = %s, cursando = %s, cursandolugar = %s, otroscursosfp = %s,
         otroscursosfpcuales = %s, jefefamilia = %s, deportes = %s, deportesdonde = %s,
         tiempolibre = %s, eligioelcentro = %s, eligioelcurso = %s, judiciales = %s, causas = %s,
         tratmedico = %s, observaciones = %s WHERE id_legajo = %s''', (self.idalumnoB, nombre, fechanac, 
         lugarNac, estcivil, domicilio, telefono, planSocial, queplan, planFamiliar, queplanfamiliar,
         empleo, ubicacionempleo, educformal, abandono, causaabandono, cursando, cursandolugar,
         otroscursosfp, otroscursosfpcuales, jefefamilia, deportes, deportesdonde, tiempolibre,
         eligioelcentro, eligioelcurso, judiciales, causas, tratmedico, observaciones, self.id))
        # Cargo el grupo familiar
        c.execute('''TRUNCATE TABLE `grupoFam_%s`''' % int(self.idalumnoB))
        lista = []
        for i in range(10):
            tupla =[]
            for j in range(5):
                a = self.gridFamilia.GetCellValue(i, j)
                tupla.append(a)
            t = tuple(tupla)
            lista.append(t)
        for tupla in lista:
            c.execute('''INSERT INTO `grupoFam_%s` (nombre, parentesco, edad, trabajo, 
                obs) VALUES (%s, %s, %s, %s, %s)''', (int(self.idalumnoB), tupla[0], tupla[1],
                 tupla[2], tupla[3], tupla[4]))
        c.close()
        wx.MessageBox(u'Operación realizada con éxito', u'Actualización de Legajo social', wx.OK | wx.ICON_INFORMATION, self)
        self.Close()
        
    def OnAbrirArchivo(self, event):
        import editor
        ventana = editor.RichTextFrame(self, -1, u'Editor de textos de Sancabase', size=(700, 500), style = wx.DEFAULT_FRAME_STYLE)
        ventana.CenterOnScreen()
        ventana.Show(True)
        
    def OnCancelar(self, event): # wxGlade: LegajoSocial.<event_handler>
        self.Close()

# end of class LegajoSocial


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame = LegajoSocialCargado(None, -1, "")
    app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()
