#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Jan 31 13:24:27 2010

import wx
import MySQLdb
import sys

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # Conectarse a la db
        self.db = MySQLdb.connect('localhost', 'javier', 'javier', 'escuela', charset='UTF8')
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.panel = wx.Panel(self, -1)
        f=open('seguimiento', 'r')
        self.numero = f.readline()
        f.close()
        c = self.db.cursor()
        c.execute('''SELECT DISTINCT apellidos, nombres FROM alumnos WHERE id_alumno = %s''', (self.numero))
        q = c.fetchone()
        c.close()
        self.labelSegui = wx.StaticText(self.panel, -1, "Egresado/a: %s %s" % (q[1],q[0]))
        self.static_line_1 = wx.StaticLine(self.panel, -1)
        self.listSeguimiento = wx.ListCtrl(self.panel, -1, style=wx.LC_REPORT|wx.LC_SORT_ASCENDING|wx.SUNKEN_BORDER)
        self.btnAceptar = wx.Button(self.panel, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnAceptar, self.btnAceptar)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Seguimiento de egresados")
        self.SetSize((611, 426))
        self.labelSegui.SetFont(wx.Font(18, wx.SWISS, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade
        columnas = [u'Rubro', u'Empresa', u'Estado', u'Fecha']
        for col, text in enumerate(columnas):
            self.listSeguimiento.InsertColumn(col, text)
        self.listSeguimiento.SetColumnWidth(0, 150)
        self.listSeguimiento.SetColumnWidth(1, 150)
        self.listSeguimiento.SetColumnWidth(2, 150)
        self.listSeguimiento.SetColumnWidth(3, 150)
        c = self.db.cursor()
        c.execute('''SELECT rubro, empresa, estado,
             fecha FROM seguimiento WHERE id_alumno = %s''', (self.numero))
        q = c.fetchall()
        for elemento in q:
            index = self.listSeguimiento.InsertStringItem(sys.maxint, elemento[0])
            for col, text in enumerate(elemento[1:]):
                self.listSeguimiento.SetStringItem(index, col+1, str(text))
        c.close()

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizerppal = wx.BoxSizer(wx.VERTICAL)
        sizerVert = wx.BoxSizer(wx.VERTICAL)
        sizerBtn = wx.BoxSizer(wx.HORIZONTAL)
        sizerVert.Add(self.labelSegui, 0, 0, 0)
        sizerVert.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizerVert.Add(self.listSeguimiento, 1, wx.ALL|wx.EXPAND, 5)
        sizerBtn.Add(self.btnAceptar, 0, wx.ALL|wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM, 5)
        sizerVert.Add(sizerBtn, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        self.panel.SetSizer(sizerVert)
        sizerppal.Add(self.panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizerppal)
        self.Layout()
        self.Centre()
        # end wxGlade


    def OnAceptar(self, event): # wxGlade: MyFrame.<event_handler>
        self.Close()
        
# end of class MyFrame


class Seguimiento(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frameSegu = MyFrame(None, -1, "")
        self.SetTopWindow(frameSegu)
        frameSegu.Show()
        return 1

# end of class Seguimiento

if __name__ == "__main__":
    app = Seguimiento(0)
    app.MainLoop()
