#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Dec 27 08:34:58 2009

import wx

# begin wxGlade: extracode
# end wxGlade



class SelecDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SelecDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_tit = wx.StaticText(self, -1, u"Seleccione el año a reportar:")
        self.sca = wx.SpinCtrl(self, -1, "2009", min=1990, max=2100)
        self.btnAceptar = wx.Button(self, wx.ID_APPLY, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnSeleccAnioEnCurso, self.btnAceptar)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SelecDialog.__set_properties
        self.SetTitle(u'Estadísticas anuales')
        self.SetSize((250, 180))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SelecDialog.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.label_tit, 0, wx.ALL, 5)
        sizer.Add(self.sca, 0, wx.LEFT|wx.TOP|wx.BOTTOM, 19)
        sizer.Add(self.btnAceptar, 0, wx.ALL|wx.ALIGN_RIGHT, 10)
        self.SetSizer(sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnSeleccAnioEnCurso(self, evt):
        anio = self.sca.GetValue()
        f=open('selec_anio', 'w')
        f.write('%s' % str(anio))
        f.close()
        self.Close()

# end of class SelecDialog


if __name__ == "__main__":
    dialogSelecAnio = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    anio_selec_dialog = SelecDialog(None, -1, "")
    dialogSelecAnio.SetTopWindow(anio_selec_dialog)
    anio_selec_dialog.Show()
    dialogSelecAnio.MainLoop()
